name: Benchmark
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run Benchmarks
        run: pnpm exec turbo run start --filter=benchmark
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: packages/benchmark/benchmark/results
