name: Code Inspection
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Check Code Formatting
        run: npm run check:formatting
      - name: Check Types
        run: npm run check:types
      #        No linters for this repo
      #      - name: Lint
      #        run: |
      #          npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
